name: Deploy-Azure-Bicep


on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-bicep-github-actions
  WEBAPP_NAME: webapp

jobs:
  preview-bicep-changes:
    
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: Azure/login@v1.4.3
        with:
          # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Resource Group
        run: |
          az version
          az group create -n $RESOURCE_GROUP -l westeurope
        env:
          RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
      - name: Preview Changes
        run: |
          az deployment group what-if \
            --resource-group $RESOURCE_GROUP \
            --template-uri https://raw.githubusercontent.com/Boutheinahamdi/BicepTest/main/main.bicep
          # Add any additional Azure CLI commands here
        env:
          RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
           
  deploy-azure-bicep-dev:
    environment: dev
    needs: [preview-bicep-changes]
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Azure
        uses: Azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Azure Resource Group
        uses: Azure/cli@v1.0.6
        with:
          inlineScript: |
            az version
            az group create -n $RESOURCE_GROUP -l westeurope

      - name: Deploy Bicep to Azure
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          templateFile: https://raw.githubusercontent.com/Boutheinahamdi/BicepTest/main/main.bicep

          parameters: webAppName=${{ env.WEBAPP_NAME }}
          failOnStdErr: false
